# Generated by Django 4.2.27 on 2025-12-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearshHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.IntegerField(blank=True, null=True)),
                ("pressure", models.IntegerField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
