# Generated by Django 4.2.27 on 2025-12-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_searchhistory_delete_searshhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchhistory",
            name="pressure",
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="humidity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="temperature",
            field=models.FloatField(),
        ),
    ]
